version: '2.29'

services:    
  backend:
    build: ./seniorLove-back-deploy
    env_file:
      - ./seniorLove-back-deploy/.env
    ports:
      - 4000:4000  
    depends_on:
      - db
  
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 8080:80
    volumes:
      - ./seniorLove-front-deploy/dist/:/usr/share/nginx/html
      - ./seniorLove-front-deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
     
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432

    healthcheck:
        test: [ "CMD", "pg_isready" ]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  db-data:

  
    
